const employees = [
  {
    id: 1,
    parentId: "",
    name: "John",
    positionName: "CEO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    parentId: "1",
    name: "Smith",
    positionName: "COO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/20.jpg",
  },

  {
    id: 6,
    parentId: "2",
    name: "Kate",
    positionName: "HR Manager",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 7,
    parentId: "2",
    team: "HR team",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 8,
    parentId: "2",
    name: "Erica",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    parentId: "3",
    name: "Paul",
    positionName: "Developer",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 3,
    parentId: "1",
    team: "Developers",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 10,
    parentId: "3",
    name: "Tony",
    positionName: "Lead",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 11,
    parentId: "3",
    name: "Sally",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 12,
    parentId: "4",
    name: "Scott",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },

  {
    id: 4,
    parentId: "1",
    name: "James",
    positionName: "CTO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 13,
    parentId: "4",
    name: "Tony",
    positionName: "Lead",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 14,
    parentId: "4",
    name: "Sally",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 15,
    parentId: "6",
    name: "Scott",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },

  {
    id: 5,
    parentId: "6",
    name: "James",
    positionName: "CTO",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 16,
    parentId: "7",
    name: "Tony",
    positionName: "Lead",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 17,
    parentId: "7",
    name: "Sally",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 18,
    parentId: "8",
    name: "Scott",
    positionName: "Teacher",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "LA Branch",
    department: "Marketing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },
];

export default employees;
